### ISSUE TITLE
common: got error while using unixSocket

### ISSUE THREAD

**Issue by KAVAN-DESAI** [dart-lightning/lndart.cln#60]
got some error in calling getInfo method using unixSocket
```flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   LogManager.info (package:cln_common/src/logger/logger_manager.dart:24:13)
flutter: │ #1   RPCClient.connect (package:clightning_rpc/src/clightning_rpc.dart:10:10)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 💡 Connection to JSON RPC 2.0 at the following path /root/.lightning/testnet
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _Exception was thrown building FutureBuilder<AppGetInfo>(dirty, state:
_FutureBuilderState<AppGetInfo>#0554d):
Exception: Converting object to an encodable object failed: Instance of 'JsonRpcMethod'

The relevant error-causing widget was:
  FutureBuilder<AppGetInfo>
  FutureBuilder:file:///home/kavan/AndroidStudioProjects/lndart.clnapp/lib/views/home/home_view.dart:181:12

When the exception was thrown, this was the stack:
#0      _HomeViewState._checkIfThereAreError (package:clnapp/views/home/home_view.dart:176:7)
#1      _HomeViewState._buildMainView.<anonymous closure> (package:clnapp/views/home/home_view.dart:184:11)
#2      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:615:55)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#12     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by vincenzopalazzo** [comment]
Related https://www.autoscripts.net/error-converting-object-to-an-encodable-object-failed-instance-of-sendcart/
